config/routes.rb
Rails.application.routes.draw do

  scope ":locale", :locale => /#{I18n.available_locales.join("|")}/ do 

    devise_for :customer 
    devise_for :admin, :skip => [:registrations] 

    namespace :admin do
      # CRUD nested category, product, image
      resources :categories do 
        resources :products do 
          resources :product_images, :as => :images
        end
      end

      # View orders route
      get '/view-orders', :to => 'orders#view_orders'
      get '/', :to => 'categories#index'
    end

    namespace :customer do 
      get '/', :to => 'account#my_account'
      get '/edit-account-information', :to => 'account#edit_account_information'
      patch '/edit-account-information', :to => 'account#edit_customer'

      get '/view-carts', :to => 'orders#view_carts'
      get '/checkout', :to => 'orders#checkout'
      get '/view-orders', :to => 'orders#view_orders'
      post '/checkout', :to => 'orders#make_an_order'
      delete '/remove-this-cart/:id', :to => 'orders#remove_cart', :as => 'remove_this_cart'
      post '/cart', :to => 'orders#add_to_cart'
    end

    scope :module => :home do
      root :to => 'home#index'

      get '/categories/:id', :to => 'home#show_category', :as => 'group_products'
      get '/product/:id', :to => 'home#show_product', :as => 'product_detail'
      get '/contact-us', :to => 'home#contact'
      get '/about-us', :to => 'home#about'
    end

  end

  get '', :to => redirect("/#{I18n.default_locale}")

end

app/models/customer.rb
class Customer < User
end

app/controllers/customer/account_controller.rb
class Customer::AccountController < ApplicationController
  before_filter :authenticate_customer!

  # GET / or /my-account
  def my_account
    @orders = current_customer.orders.includes(:product).in_order || []
  end
  
  # GET /edit-account-information
  def edit_account_information
  end

  # PATCH /edit-account-information
  def edit_customer
  end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_filter :authenticate_customer!

  # GET /customer/view-carts
  def view_carts
    page = params[:page] || 1
    @carts = current_customer.orders.includes(:product => [:product_images]).cart.page(page).per(5) || []
  end

  # GET /customer/view-orders
  def view_orders
    page = params[:page] || 1
    @orders = current_customer.orders.includes(:product).in_order.page(page).per(5) || []
  end

  # GET /customer/checkout 
  def checkout
    @carts = current_customer.orders.includes(:product).cart || []
  end

  # POST /customer/add-to-cart
  def add_to_cart
    begin
      order = Order.new(
        :product_id => params[:id], 
        :date => Date.today, 
        :quantity => 1, 
        :state => 1
      )
      current_customer.orders << order
      cart = current_customer.orders.includes(:product).includes(:product_images).cart

      render :json => cart if request.xhr? >= 0
    rescue 
      puts 'errors'
    end
  end

  # GET /customer/make-an-order
  def make_an_order
    current_customer.orders.cart.update_all(:state => 2)
    render :json => { code: 200 } if request.xhr? >= 0
  end

  # DELETE /customer/remove-cart
  def remove_cart
    cart = Order.find(params[:id])

    cart.destroy
    redirect_to customer_path
  end

end

app/views/customer/shared/_links.slim
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  br/

app/views/customer/shared/_sidebar.slim
.block.block-account.first
  .block-title
    strong
      span = t 'homepage.my_account'
  .block-content
    ul
      li
        = link_to t("customer.dashboard"), customer_path 
      li
        = link_to t("customer.change_pass"), edit_customer_registration_path
      li
        = link_to t("customer.change_info"), customer_edit_account_information_path
      li
        = link_to t("customer.view_cart"), customer_view_carts_path
      li 
        = link_to t("customer.view_orders"), customer_view_orders_path
      li
        = link_to t("customer.checkout"), customer_checkout_path