config/routes.rb
Rails.application.routes.draw do

  scope ":locale", :locale => /#{I18n.available_locales.join("|")}/ do 

    devise_for :customer 
    devise_for :admin, :skip => [:registrations] 

    namespace :admin do
      # CRUD nested category, product, image
      resources :categories do 
        resources :products do 
          resources :product_images, :as => :images
        end
      end

      # View orders route
      get '/view-orders', :to => 'orders#view_orders'
      get '/', :to => 'categories#index'
    end

    namespace :customer do 
      get '/', :to => 'account#my_account'
      get '/edit-account-information', :to => 'account#edit_account_information'
      patch '/edit-account-information', :to => 'account#edit_customer'

      get '/view-carts', :to => 'orders#view_carts'
      get '/checkout', :to => 'orders#checkout'
      get '/view-orders', :to => 'orders#view_orders'
      post '/checkout', :to => 'orders#make_an_order'
      delete '/remove-this-cart/:id', :to => 'orders#remove_cart', :as => 'remove_this_cart'
      post '/cart', :to => 'orders#add_to_cart'
    end

    scope :module => :home do
      root :to => 'home#index'

      get '/categories/:id', :to => 'home#show_category', :as => 'group_products'
      get '/product/:id', :to => 'home#show_product', :as => 'product_detail'
      get '/contact-us', :to => 'home#contact'
      get '/about-us', :to => 'home#about'
    end

  end

  get '', :to => redirect("/#{I18n.default_locale}")

end

app/views/shared/_cart_item.slim
li.item
  .product-control-buttons
    = link_to 'Remove This Item', customer_remove_this_cart_path(cart), :method => :delete, data: { :confirm => 'Are you sure?' }, :class => 'btn-remove'
  = link_to product_detail_path(cart.product.id), :title => cart.product.name, :class => 'product-image' do 
    = image_tag cart.product.product_images[0].image.url, :alt => cart.product.name if cart.product.product_images.size > 0
  p.product-name
    = link_to cart.product.name, product_detail_path(cart.product.id), :title => cart.product.name
  .product-details
    strong 1
    | x
    span.price = cart.product.price

app/views/shared/_footer.slim
.container
  .row
    .col-md-12.col-xs-12
      .footer
        .footer-cols-wrapper

          .col-md-3.col-xs-12.footer-col

          .col-md-3.col-xs-12.footer-col

          .col-md-2.col-xs-12.footer-col
            h4 = t('homepage.my_account') 
            .footer-col-content
              ul
                li
                  = link_to t('homepage.login'), customer_session_path
                li
                  = link_to t('customer.view_cart'), customer_view_carts_path
                li
                  = link_to t('customer.dashboard'), customer_path

          .col-md-4.col-xs-12.footer-col.contacts
            h4 = t('homepage.contacts') 
            .footer-col-content
              p
                - if I18n.locale == :en
                  i.fa.fa-map-marker
                  | JSC Investment Consultant Thanh Nam,
                  br
                  | No 26 K3, Nguyen Phong Sac, Cau Giay, Ha Noi
                - else 
                  i.fa.fa-map-marker
                  | Công ty Cổ phần Tư vấn Đầu tư Thành Nam,
                  br
                  | Số 26 K3, Nguyễn Phong Sắc, Cầu Giấy, Hà Nội
              p.tel 
                i.fa.fa-phone
                | Phone: (043)3787-8631
        .clear

app/views/shared/_header.slim
.header-container.header
  .container
    = render '/shared/top_header'

  .nav-container
    = render '/shared/nav'
  

app/views/shared/_nav.slim
.container
  .row
    ul#nav.sf-menu.sf-js-enabled
      - if @category_banner.size > 0
        - @category_banner.collect do |nav_item| 
          = content_tag :li, :class => (current_page?(group_products_path(nav_item)) ? 'active' : '') 
            = link_to group_products_path(nav_item) do 
              span = nav_item.name
      - else 
        li.level0.nav-2.level-top
          a.level-top href="#" 
            span Activewear
        li.level0.nav-3.level-top
          a.level-top href="#" 
            span Casual Shirts
        li.level0.nav-4.level-top
          a.level-top href="#" 
            span Jeans &amp; Pants
        li.level0.nav-5.level-top.parent
          a.level-top href="#" 
            span Outerwear
        li.level0.nav-6.last.level-top
          a.level-top href="#" 
            span Pajamas &amp; Robes

app/views/shared/_top_header.slim
.row
  .col-md-12.col-xs-12 
    .header

      .header-buttons
        .header-button.lang-list
          a href="#" 
            - if I18n.locale == :en
              | en
            - else 
              | vi
            i.fa.fa-chevron-circle-down
          ul
            li
              = link_to_unless_current "vi", :locale => 'vi' 
                span vi
            li
              = link_to_unless_current "en", :locale => 'en'
                span en

      .header-links
        ul.links
          li.first
            = link_to t('homepage.my_account'), customer_path
          li
            = link_to t('homepage.checkout'), customer_checkout_path
          - if customer_signed_in?
            li
              = link_to t('homepage.my_cart'), customer_view_carts_path
            li.last
              = link_to t('homepage.logout'), destroy_customer_session_path, :method => :delete
          - else 
            li.last
              = link_to t('homepage.login'), new_customer_session_path
  
      .clear

      h1.logo
        strong Shining Kids
        = link_to root_path do
          img alt=("Shining Kids") src="/images/logo.gif" 

      .quick-access
      
        .row-2
          .block-cart-header
            i.fa.fa-chevron-circle-down
            h3 = t('homepage.my_cart') + ':'
            .block-content
              .empty
                = @carts.size
                span = t('homepage.item') + ' -'
                span.price 
                  | &nbsp;
                  = @carts.inject(0){|sum,x| sum + x.product.price}
                .cart-content style=("display: none;") 
                  .cart-indent
                    p.subtotal
                      span.label = t("homepage.subtotal")
                      span.price 0
                    p.block-subtitle = t("homepage.recent_item")
                    ol#cart-sidebar.mini-products-list
                      - if @carts.size > 0
                        - @carts.each_with_index do |cart, i|
                          = render 'shared/cart_item', :cart => cart if i < 3
                      - else
                        li.item = t("homepage.empty")
                    .actions
                      button.button onclick="window.location.replace(window.location.origin + '/' + window.location.pathname.split('/')[1] + '/customer/checkout');" title="Checkout" type="button" 
                        span
                          span = t('homepage.checkout')
                      button.button onclick="window.location.replace(window.location.origin + '/' + window.location.pathname.split('/')[1] + '/customer/view-carts');" title=("My Cart") type="button" 
                        span
                          span = t('homepage.my_cart')

        form#search_mini_form action="search.html" method="get" 
          .form-search
            label for="search"  Search:
            input#search.input-text autocomplete="off" maxlength="128" name="q" type="text" value="" 
              button.button title="Search" type="submit" 
                strong
                  i.fa.fa-search.icon-search
                #search_autocomplete.search-autocomplete style=("display: none;") 
        .clear

      .clear