config/routes.rb
Rails.application.routes.draw do

  scope ":locale", :locale => /#{I18n.available_locales.join("|")}/ do 

    devise_for :customer 
    devise_for :admin, :skip => [:registrations] 

    namespace :admin do
      # CRUD nested category, product, image
      resources :categories do 
        resources :products do 
          resources :product_images, :as => :images
        end
      end

      # View orders route
      get '/view-orders', :to => 'orders#view_orders'
      get '/', :to => 'categories#index'
    end

    namespace :customer do 
      get '/', :to => 'account#my_account'
      get '/edit-account-information', :to => 'account#edit_account_information'
      patch '/edit-account-information', :to => 'account#edit_customer'

      get '/view-carts', :to => 'orders#view_carts'
      get '/checkout', :to => 'orders#checkout'
      get '/view-orders', :to => 'orders#view_orders'
      post '/checkout', :to => 'orders#make_an_order'
      delete '/remove-this-cart/:id', :to => 'orders#remove_cart', :as => 'remove_this_cart'
      post '/cart', :to => 'orders#add_to_cart'
    end

    scope :module => :home do
      root :to => 'home#index'

      get '/categories/:id', :to => 'home#show_category', :as => 'group_products'
      get '/product/:id', :to => 'home#show_product', :as => 'product_detail'
      get '/contact-us', :to => 'home#contact'
      get '/about-us', :to => 'home#about'
    end

  end

  get '', :to => redirect("/#{I18n.default_locale}")

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products, :dependent => :destroy

  validates :name, :presence => true, :uniqueness => { case_sensitive: false }

  has_attached_file :image, :style => { :medium => "300x300" }, 
        :path => ":rails_root/public/images/category_image/:id/:basename.:extension",
        :url => "/images/category_image/:id/:basename.:extension"

  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  validates_attachment_size :image, :less_than => 3.megabytes

  def name
    if I18n.locale == :en 
      read_attribute :name
    else
      read_attribute('name_' + I18n.locale.to_s)
    end
  end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :set_admin_category, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_admin!

  # GET /admin/categories
  def index
    @admin_categories = Category.all
  end

  # GET /admin/categories/1
  def show
  end

  # GET /admin/categories/new
  def new
    @admin_category = Category.new
  end

  # GET /admin/categories/1/edit
  def edit
  end

  # POST /admin/categories
  def create
    @admin_category = Category.new(admin_category_params)

    if @admin_category.save
      redirect_to admin_category_path(@admin_category), notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /admin/categories/1
  def update
    if @admin_category.update(admin_category_params)
      redirect_to admin_category_path(@admin_category), notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admin/categories/1
  def destroy
    @admin_category.destroy
    redirect_to admin_categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_category
      @admin_category = Category.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def admin_category_params
      params.require(:category).permit(:name, :description, :image, :name_vi)
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_form.slim
= form_for @admin_category, :url => url, :method => method do |f|
  - if @admin_category.errors.any?
    #error_explanation
      h2
        = pluralize(@admin_category.errors.count, "error")
        | prohibited this admin_category from being saved:
      ul
        - @admin_category.errors.full_messages.each do |message|
          li= message
  .field
    = f.label :name
    br
      = f.text_field :name
  .field
    = f.label :name_vi
    br
      = f.text_field :name_vi
  .field
    = f.label :description
    br
      = f.text_area :description, :size => '50x10'
  .field
    = f.label :image
    br
      = f.file_field :image, :class => 'btn', :class => 'form-control'
  .actions
    = f.submit

app/views/admin/categories/edit.slim
= content_for :main_content

  .header-bg
    = render '/shared/header'

  .main-container-tile
    .main-container.col2-right-layout
      .container
        .row
          .col-md-12.col-xs-12
            .main
              .row
                .col-left.sidebar.col-md-3.col-xs-12
                  .block.block-account.first
                    .block-title
                      strong
                        span Admin
                    .block-content
                      ul
                        li
                          = link_to "Admin dashboard", admin_path
                        li
                          = link_to "Category", admin_categories_path
                        li 
                          = link_to "View Orders", admin_view_orders_path

                .col-main.col-md-9.col-xs-12
                  .padding-s
                    .page-title.category-title
                      h1 Editing category
                    = render 'form', :url => admin_category_path(@admin_category), :method => :patch
                    = link_to 'Show', admin_category_path(@admin_category)
                    |- #{link_to 'Back', admin_categories_path}

  .clear

  .footer-container
    = render '/shared/footer'

= content_for :page_footer
  = javascript_include_tag 'home/show_category'

= content_for :page_header
  = stylesheet_link_tag 'home/show_category', media: 'all'  

app/views/admin/categories/index.slim
= content_for :main_content

  .header-bg
    = render '/shared/header'

  .main-container-tile
    .main-container.col2-right-layout
      .container
        .row
          .col-md-12.col-xs-12
            .main
              .row
                .col-left.sidebar.col-md-3.col-xs-12
                  .block.block-account.first
                    .block-title
                      strong
                        span Admin
                    .block-content
                      ul
                        li
                          = link_to "Admin dashboard", admin_path
                        li
                          = link_to "Category", admin_categories_path
                        li 
                          = link_to "View Orders", admin_view_orders_path

                .col-main.col-md-9.col-xs-12
                  .padding-s
                    .page-title.category-title
                      h1 Listing Categories

                    table.table
                      thead
                        tr
                          th Image
                          th Name
                          th Description
                          th List fo products
                          th colspan="3" 
                      tbody
                        - @admin_categories.each do |admin_category|
                          tr
                            td= image_tag admin_category.image.url, :class => 'img-responsive'
                            td= admin_category.name
                            td= admin_category.description
                            td= link_to 'List of products', admin_category_products_path(admin_category)
                            td= link_to 'Show', admin_category_path(admin_category)
                            td= link_to 'Edit', edit_admin_category_path(admin_category)
                            td= link_to 'Destroy', admin_category_path(admin_category), method: :delete, data: { :confirm => 'Are you sure?' }
                    br
                      = link_to 'New Category', new_admin_category_path

  .clear

  .footer-container
    = render '/shared/footer'

= content_for :page_footer
  = javascript_include_tag 'home/show_category'

= content_for :page_header
  = stylesheet_link_tag 'home/show_category', media: 'all'  

app/views/admin/categories/new.slim
= content_for :main_content

  .header-bg
    = render '/shared/header'

  .main-container-tile
    .main-container.col2-right-layout
      .container
        .row
          .col-md-12.col-xs-12
            .main
              .row
                .col-left.sidebar.col-md-3.col-xs-12
                  .block.block-account.first
                    .block-title
                      strong
                        span Admin
                    .block-content
                      ul
                        li
                          = link_to "Admin dashboard", admin_path
                        li
                          = link_to "Category", admin_categories_path
                        li 
                          = link_to "View Orders", admin_view_orders_path

                .col-main.col-md-9.col-xs-12
                  .padding-s
                    .page-title.category-title
                      h1 New Category
                    = render 'form', :url => admin_categories_path, :method => :post
                    = link_to 'Back', admin_categories_path

  .clear

  .footer-container
    = render '/shared/footer'

= content_for :page_footer
  = javascript_include_tag 'home/show_category'

= content_for :page_header
  = stylesheet_link_tag 'home/show_category', media: 'all'  

app/views/admin/categories/show.slim
= content_for :main_content

  .header-bg
    = render '/shared/header'

  .main-container-tile
    .main-container.col2-right-layout
      .container
        .row
          .col-md-12.col-xs-12
            .main
              .row
                .col-left.sidebar.col-md-3.col-xs-12
                  .block.block-account.first
                    .block-title
                      strong
                        span Admin
                    .block-content
                      ul
                        li
                          = link_to "Admin dashboard", admin_path
                        li
                          = link_to "Category", admin_categories_path
                        li 
                          = link_to "View Orders", admin_view_orders_path

                .col-main.col-md-9.col-xs-12
                  .padding-s
                    .page-title.category-title
                      h1 = @admin_category.name

                    p#notice= notice
                    p
                      strong Description:
                      = @admin_category.description
                    p
                      strong Image:
                      = image_tag @admin_category.image.url, :class => 'img-responsive'

                      = link_to 'Edit', edit_admin_category_path(@admin_category)
                    |- #{link_to 'Back', admin_categories_path}

  .clear

  .footer-container
    = render '/shared/footer'

= content_for :page_footer
  = javascript_include_tag 'home/show_category'

= content_for :page_header
  = stylesheet_link_tag 'home/show_category', media: 'all'  