config/routes.rb
Rails.application.routes.draw do

  scope ":locale", :locale => /#{I18n.available_locales.join("|")}/ do 

    devise_for :customer 
    devise_for :admin, :skip => [:registrations] 

    namespace :admin do
      # CRUD nested category, product, image
      resources :categories do 
        resources :products do 
          resources :product_images, :as => :images
        end
      end

      # View orders route
      get '/view-orders', :to => 'orders#view_orders'
      get '/', :to => 'categories#index'
    end

    namespace :customer do 
      get '/', :to => 'account#my_account'
      get '/edit-account-information', :to => 'account#edit_account_information'
      patch '/edit-account-information', :to => 'account#edit_customer'

      get '/view-carts', :to => 'orders#view_carts'
      get '/checkout', :to => 'orders#checkout'
      get '/view-orders', :to => 'orders#view_orders'
      post '/checkout', :to => 'orders#make_an_order'
      delete '/remove-this-cart/:id', :to => 'orders#remove_cart', :as => 'remove_this_cart'
      post '/cart', :to => 'orders#add_to_cart'
    end

    scope :module => :home do
      root :to => 'home#index'

      get '/categories/:id', :to => 'home#show_category', :as => 'group_products'
      get '/product/:id', :to => 'home#show_product', :as => 'product_detail'
      get '/contact-us', :to => 'home#contact'
      get '/about-us', :to => 'home#about'
    end

  end

  get '', :to => redirect("/#{I18n.default_locale}")

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_one :order
  has_many :product_images, :dependent => :destroy

  validates :name, :presence => true, :uniqueness => { case_sensitive: false }

  def name
    if I18n.locale == :en 
      read_attribute :name
    else
      read_attribute('name_' + I18n.locale.to_s)
    end
  end

  def price
    if I18n.locale == :en 
      read_attribute :price
    else
      read_attribute('price_' + I18n.locale.to_s)
    end
  end

  def saleoff
    if I18n.locale == :en 
      read_attribute :saleoff
    else
      read_attribute('saleoff_' + I18n.locale.to_s)
    end
  end

  def description
    if I18n.locale == :en 
      read_attribute :description
    else
      read_attribute('name_' + I18n.locale.to_s)
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :set_product
  before_filter :authenticate_admin!

  # GET /products
  def index
    @products = @category.products
  end

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to admin_category_product_path(@category, @product), notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to admin_category_product_path(@category, @product), notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to admin_category_products_url, notice: 'Product was successfully destroyed.'
  end

  private
  def set_product
    @category = Category.find(params[:category_id])
    @product = @category.products.find(params[:id]) if params[:id]
  end

  def product_params
    params.require(:product).permit(:name, :price, :saleoff, :description, :category_id, :name_vi, :description_vi, :price_vi, :saleoff_vi)
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_form.slim
= form_for [@category, @product], :url => url do |f|
  - if @product.errors.any?
    #error_explanation
      h2
        = pluralize(@product.errors.count, "error")
        | prohibited this product from being saved:
      ul
        - @product.errors.full_messages.each do |message|
          li= message
  .field
    = f.hidden_field :category_id, :value => @category.id
  .field
    = f.label :name
    br
      = f.text_field :name
  .field
    = f.label :name_vi
    br
      = f.text_field :name_vi
  .field
    = f.label :price
    br
      = f.text_field :price
  .field
    = f.label :price_vi
    br
      = f.text_field :price_vi
  .field
    = f.label :saleoff
    br
      = f.text_field :saleoff
  .field
    = f.label :saleoff_vi
    br
      = f.text_field :saleoff_vi
  .field
    = f.label :description
    br
      = f.text_area :description, :size => '50x10'
  .field
    = f.label :description_vi
    br
      = f.text_area :description_vi, :size => '50x10'

  .actions
    = f.submit

app/views/admin/products/edit.slim
- content_for :main_content

  .header-bg
    = render '/shared/header'

  .main-container-tile
    .main-container.col2-right-layout
      .container
        .row
          .col-md-12.col-xs-12
            .main
              .row
                .col-left.sidebar.col-md-3.col-xs-12
                  .block.block-account.first
                    .block-title
                      strong
                        span Admin
                    .block-content
                      ul
                        li
                          = link_to "Admin dashboard", admin_path
                        li
                          = link_to "Category", admin_categories_path
                        li 
                          = link_to "View Orders", admin_view_orders_path

                .col-main.col-md-9.col-xs-12
                  .padding-s
                    .page-title.category-title
                      h1 Editing product
                    = render 'form', :url => admin_category_product_path 
                    = link_to 'Show', admin_category_product_path(@category, @product)
                    |- #{link_to 'Back', admin_category_products_path(@category) }

  .clear

  .footer-container
    = render '/shared/footer'

= content_for :page_footer
  = javascript_include_tag 'home/show_category'

= content_for :page_header
  = stylesheet_link_tag 'home/show_category', media: 'all'  

app/views/admin/products/index.slim
- content_for :main_content

  .header-bg
    = render '/shared/header'

  .main-container-tile
    .main-container.col2-right-layout
      .container
        .row
          .col-md-12.col-xs-12
            .main
              .row
                .col-left.sidebar.col-md-3.col-xs-12
                  .block.block-account.first
                    .block-title
                      strong
                        span Admin
                    .block-content
                      ul
                        li
                          = link_to "Admin dashboard", admin_path
                        li
                          = link_to "Category", admin_categories_path
                        li 
                          = link_to "View Orders", admin_view_orders_path

                .col-main.col-md-9.col-xs-12
                  .padding-s
                    .page-title.category-title
                      h1 Listing products

                    table.table
                      thead
                        tr
                          th Name
                          th Price
                          th Saleoff
                          th Description
                          th List of images
                          th colspan="3" 
                      tbody
                        - @products.each do |product|
                          tr
                            td= product.name
                            td= product.price
                            td= product.saleoff
                            td= product.description
                            td= link_to 'List of images', admin_category_product_images_path(@category, product)
                            td= link_to 'Show', admin_category_product_path(@category, product)
                            td= link_to 'Edit', edit_admin_category_product_path(@category, product)
                            td= link_to 'Destroy', admin_category_product_path(@category, product), method: :delete, data: { :confirm => 'Are you sure?' }
                    br
                      = link_to 'New Product', new_admin_category_product_path(@category)
                      |- #{link_to 'Back', admin_categories_path }

  .clear

  .footer-container
    = render '/shared/footer'

= content_for :page_footer
  = javascript_include_tag 'home/show_category'

= content_for :page_header
  = stylesheet_link_tag 'home/show_category', media: 'all'  

app/views/admin/products/new.slim
- content_for :main_content

  .header-bg
    = render '/shared/header'

  .main-container-tile
    .main-container.col2-right-layout
      .container
        .row
          .col-md-12.col-xs-12
            .main
              .row
                .col-left.sidebar.col-md-3.col-xs-12
                  .block.block-account.first
                    .block-title
                      strong
                        span Admin
                    .block-content
                      ul
                        li
                          = link_to "Admin dashboard", admin_path
                        li
                          = link_to "Category", admin_categories_path
                        li 
                          = link_to "View Orders", admin_view_orders_path

                .col-main.col-md-9.col-xs-12
                  .padding-s
                    .page-title.category-title
                      h1 New product
                    = render 'form', :url => admin_category_products_path 
                    = link_to 'Back', admin_category_products_path(@category)

  .clear

  .footer-container
    = render '/shared/footer'

= content_for :page_footer
  = javascript_include_tag 'home/show_category'

= content_for :page_header
  = stylesheet_link_tag 'home/show_category', media: 'all'  

app/views/admin/products/show.slim
- content_for :main_content

  .header-bg
    = render '/shared/header'

  .main-container-tile
    .main-container.col2-right-layout
      .container
        .row
          .col-md-12.col-xs-12
            .main
              .row
                .col-left.sidebar.col-md-3.col-xs-12
                  .block.block-account.first
                    .block-title
                      strong
                        span Admin
                    .block-content
                      ul
                        li
                          = link_to "Admin dashboard", admin_path
                        li
                          = link_to "Category", admin_categories_path
                        li 
                          = link_to "View Orders", admin_view_orders_path

                .col-main.col-md-9.col-xs-12
                  .padding-s
                    .page-title.category-title
                      h1 = @product.name
                      h1 = @product.name_vi

                    p
                      strong Price:
                      = @product.price
                    p
                      strong Saleoff:
                      = @product.saleoff
                    p
                      strong Description:
                      = @product.description

                    p
                      strong Price:
                      = @product.price_vi
                    p
                      strong Saleoff:
                      = @product.saleoff_vi
                    p
                      strong Description:
                      = @product.description_vi

                    = link_to 'Edit', edit_admin_category_product_path(@category, @product)
                    |- #{link_to 'Back', admin_category_products_path(@category) }

  .clear

  .footer-container
    = render '/shared/footer'

= content_for :page_footer
  = javascript_include_tag 'home/show_category'

= content_for :page_header
  = stylesheet_link_tag 'home/show_category', media: 'all'  